# Generated by Django 4.0.6 on 2022-07-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Enlace'),
        ),
    ]
